This notebook shows how to use the washover module. In particular, it shows how to apply a ConstantWashover object with a 30min time delta.

In [1]:
## Import Libraries

import numpy as np
import pandas as pd
from datetime import datetime, timedelta

from cluster_experiments import ConstantWashover

In [5]:
## Generate a dummy dataset of 4 time periods of 2 hours with 10 orders each

np.random.seed(42)

num_rows = 10

def random_timestamp(start_time, end_time):
    time_delta = end_time - start_time
    random_seconds = np.random.randint(0, time_delta.total_seconds())
    return start_time + timedelta(seconds=random_seconds)

def generate_data(start_time, end_time, treatment):
    data = {
        'order_id': np.random.randint(10**9, 10**10, size=num_rows),
        'city_code': 'VAL',
        'activation_time_local': [random_timestamp(start_time, end_time) for _ in range(num_rows)],
        'bin_start_time_local': start_time,
        'treatment': treatment
    }
    return pd.DataFrame(data)

start_times = [datetime(2024, 1, 22, 9, 0), datetime(2024, 1, 22, 11, 0),
               datetime(2024, 1, 22, 13, 0), datetime(2024, 1, 22, 15, 0)]

treatments = ['control', 'variation', 'variation', 'control']

dataframes = [generate_data(start, start + timedelta(hours=2), treatment) for start, treatment in zip(start_times, treatments)]

df = pd.concat(dataframes).sort_values(by='activation_time_local').reset_index(drop=True)

df.head(40)

      order_id city_code activation_time_local bin_start_time_local  treatment
0   5298312065       VAL   2024-01-22 09:21:07  2024-01-22 09:00:00    control
1   5325316860       VAL   2024-01-22 09:25:28  2024-01-22 09:00:00    control
2   8395928407       VAL   2024-01-22 09:31:39  2024-01-22 09:00:00    control
3   1787846414       VAL   2024-01-22 09:45:34  2024-01-22 09:00:00    control
4   3563451924       VAL   2024-01-22 09:50:05  2024-01-22 09:00:00    control
5   3253890010       VAL   2024-01-22 09:53:22  2024-01-22 09:00:00    control
6   5495394815       VAL   2024-01-22 09:59:16  2024-01-22 09:00:00    control
7   5684118973       VAL   2024-01-22 10:04:50  2024-01-22 09:00:00    control
8   5537253172       VAL   2024-01-22 10:17:38  2024-01-22 09:00:00    control
9   3652062880       VAL   2024-01-22 10:56:15  2024-01-22 09:00:00    control
10  8140478823       VAL   2024-01-22 11:02:41  2024-01-22 11:00:00  variation
11  8767007473       VAL   2024-01-22 11:25:00  2024-01-22 11:00:00  variation
12  1279394470       VAL   2024-01-22 11:43:33  2024-01-22 11:00:00  variation
13  5147358011       VAL   2024-01-22 12:04:03  2024-01-22 11:00:00  variation
14  7528642437       VAL   2024-01-22 12:11:37  2024-01-22 11:00:00  variation
15  6603273480       VAL   2024-01-22 12:19:58  2024-01-22 11:00:00  variation
16  9370399619       VAL   2024-01-22 12:27:05  2024-01-22 11:00:00  variation
17  2111451555       VAL   2024-01-22 12:34:35  2024-01-22 11:00:00  variation
18  5714465844       VAL   2024-01-22 12:49:05  2024-01-22 11:00:00  variation
19  8233725779       VAL   2024-01-22 12:54:33  2024-01-22 11:00:00  variation
20  1067157848       VAL   2024-01-22 13:03:20  2024-01-22 13:00:00  variation
21  5128202429       VAL   2024-01-22 13:37:58  2024-01-22 13:00:00  variation
22  9440707288       VAL   2024-01-22 13:51:39  2024-01-22 13:00:00  variation
23  8418576734       VAL   2024-01-22 13:59:21  2024-01-22 13:00:00  variation
24  3602578298       VAL   2024-01-22 14:21:15  2024-01-22 13:00:00  variation
25  9274936803       VAL   2024-01-22 14:38:12  2024-01-22 13:00:00  variation
26  4055190407       VAL   2024-01-22 14:39:19  2024-01-22 13:00:00  variation
27  3520077079       VAL   2024-01-22 14:43:04  2024-01-22 13:00:00  variation
28  2272485020       VAL   2024-01-22 14:44:38  2024-01-22 13:00:00  variation
29  7612927342       VAL   2024-01-22 14:59:21  2024-01-22 13:00:00  variation
30  5173471662       VAL   2024-01-22 15:09:23  2024-01-22 15:00:00    control
31  5704750624       VAL   2024-01-22 15:14:23  2024-01-22 15:00:00    control
32  9763595546       VAL   2024-01-22 15:29:17  2024-01-22 15:00:00    control
33  2644658402       VAL   2024-01-22 15:46:30  2024-01-22 15:00:00    control
34  4099804676       VAL   2024-01-22 16:09:51  2024-01-22 15:00:00    control
35  8941024386       VAL   2024-01-22 16:25:16  2024-01-22 15:00:00    control
36  6308514806       VAL   2024-01-22 16:40:19  2024-01-22 15:00:00    control
37  7181903227       VAL   2024-01-22 16:46:14  2024-01-22 15:00:00    control
38  4052273870       VAL   2024-01-22 16:50:28  2024-01-22 15:00:00    control
39  1866377394       VAL   2024-01-22 16:54:52  2024-01-22 15:00:00    control

In [6]:
## Define washover with 30 min duration
washover = ConstantWashover(washover_time_delta=timedelta(minutes=30))

## Apply washover to the dataframe, the orders with activation time within the first 30 minutes after every change in the treatment column, clustering by city and 2h time bin, will be dropped
df_analysis_washover = washover.washover(
    df=df,
    truncated_time_col='bin_start_time_local',
    treatment_col='treatment',
    cluster_cols=['city_code','bin_start_time_local'],
    original_time_col='activation_time_local',
)

## Check that the orders have been correctly dropped (indexes 0,1,10,11,30,31,32)
df_analysis_washover.head(40)

      order_id city_code activation_time_local bin_start_time_local  treatment
2   8395928407       VAL   2024-01-22 09:31:39  2024-01-22 09:00:00    control
3   1787846414       VAL   2024-01-22 09:45:34  2024-01-22 09:00:00    control
4   3563451924       VAL   2024-01-22 09:50:05  2024-01-22 09:00:00    control
5   3253890010       VAL   2024-01-22 09:53:22  2024-01-22 09:00:00    control
6   5495394815       VAL   2024-01-22 09:59:16  2024-01-22 09:00:00    control
7   5684118973       VAL   2024-01-22 10:04:50  2024-01-22 09:00:00    control
8   5537253172       VAL   2024-01-22 10:17:38  2024-01-22 09:00:00    control
9   3652062880       VAL   2024-01-22 10:56:15  2024-01-22 09:00:00    control
12  1279394470       VAL   2024-01-22 11:43:33  2024-01-22 11:00:00  variation
13  5147358011       VAL   2024-01-22 12:04:03  2024-01-22 11:00:00  variation
14  7528642437       VAL   2024-01-22 12:11:37  2024-01-22 11:00:00  variation
15  6603273480       VAL   2024-01-22 12:19:58  2024-01-22 11:00:00  variation
16  9370399619       VAL   2024-01-22 12:27:05  2024-01-22 11:00:00  variation
17  2111451555       VAL   2024-01-22 12:34:35  2024-01-22 11:00:00  variation
18  5714465844       VAL   2024-01-22 12:49:05  2024-01-22 11:00:00  variation
19  8233725779       VAL   2024-01-22 12:54:33  2024-01-22 11:00:00  variation
20  1067157848       VAL   2024-01-22 13:03:20  2024-01-22 13:00:00  variation
21  5128202429       VAL   2024-01-22 13:37:58  2024-01-22 13:00:00  variation
22  9440707288       VAL   2024-01-22 13:51:39  2024-01-22 13:00:00  variation
23  8418576734       VAL   2024-01-22 13:59:21  2024-01-22 13:00:00  variation
24  3602578298       VAL   2024-01-22 14:21:15  2024-01-22 13:00:00  variation
25  9274936803       VAL   2024-01-22 14:38:12  2024-01-22 13:00:00  variation
26  4055190407       VAL   2024-01-22 14:39:19  2024-01-22 13:00:00  variation
27  3520077079       VAL   2024-01-22 14:43:04  2024-01-22 13:00:00  variation
28  2272485020       VAL   2024-01-22 14:44:38  2024-01-22 13:00:00  variation
29  7612927342       VAL   2024-01-22 14:59:21  2024-01-22 13:00:00  variation
33  2644658402       VAL   2024-01-22 15:46:30  2024-01-22 15:00:00    control
34  4099804676       VAL   2024-01-22 16:09:51  2024-01-22 15:00:00    control
35  8941024386       VAL   2024-01-22 16:25:16  2024-01-22 15:00:00    control
36  6308514806       VAL   2024-01-22 16:40:19  2024-01-22 15:00:00    control
37  7181903227       VAL   2024-01-22 16:46:14  2024-01-22 15:00:00    control
38  4052273870       VAL   2024-01-22 16:50:28  2024-01-22 15:00:00    control
39  1866377394       VAL   2024-01-22 16:54:52  2024-01-22 15:00:00    control

In [7]:
print('df:', df.shape)
print('df_analysis_washover:', df_analysis_washover.shape)

df: (40, 5)
df_analysis_washover: (33, 5)